{{- if and .Values.persistence.enabled (eq .Values.persistence.type "statefulset") }}
{{- if and .Values.service.type (eq .Values.service.type "ClusterIP") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.fullname" . }}-headless
  namespace: {{ template "grafana.namespace" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
  type: ClusterIP
{{- end }}
{{- end }}
