{{- $gpu_count := index .Values.jupyter.resources.limits "nvidia.com/gpu" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tensorflow-notebook.fullname" . }}
  labels:
    app: {{ template "tensorflow-notebook.name" . }}
    chart: {{ template "tensorflow-notebook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "tensorflow-notebook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tensorflow-notebook.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/jupyter-secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              {{- if gt $gpu_count 0.0 }}
              - key: aliyun.accelerator/nvidia_count
                operator: In
                values: [{{ $gpu_count | quote }}]
              {{- else }}
              - key: gpu_node
                operator: In
                values: ["false"]
              {{- end }}
{{- if .Values.extraInitContainers }}
      initContainers:
{{ toYaml .Values.extraInitContainers | indent 8 }}
{{- end }}
      containers:
        - name: jupyter
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          imagePullPolicy: {{ .Values.jupyter.image.pullPolicy }}
          ports:
            - containerPort: 8888
              name: jupyter
          {{- if not .Values.jupyter.defaultCmd }}
          command:
            - jupyter
          args:
            - notebook
            - --allow-root
          {{- end }}
{{- if .Values.extraArgs }}
          {{- if .Values.jupyter.defaultCmd }}
          args:
          {{- end }}
{{ toYaml .Values.extraArgs | indent 12 }}
{{- end }}
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "tensorflow-notebook.fullname" . }}
                  key: password
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 12 }}
{{- end }}
          {{- if .Values.jupyter.resources }}
          resources:
            {{- toYaml .Values.jupyter.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 8888
          readinessProbe:
            httpGet:
              path: /
              port: 8888
          volumeMounts:
            - mountPath: {{ .Values.logs.mountPath }}
              name: training-logs-volume
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
        - name: tensorboard
          image: "{{ .Values.tensorboard.image.repository }}:{{ .Values.tensorboard.image.tag }}"
          imagePullPolicy: {{ .Values.tensorboard.image.pullPolicy }}
          ports:
            - containerPort: 6006
              name: tensorboard
          command:
            - tensorboard
          args:
            - --logdir
            - {{ .Values.tensorboard.logDir }}
            - --host
            - 0.0.0.0
          livenessProbe:
            httpGet:
              path: /
              port: 6006
          readinessProbe:
            httpGet:
              path: /
              port: 6006
          volumeMounts:
            - mountPath: {{ .Values.logs.mountPath }}
              name: training-logs-volume
      volumes:
        - name: training-logs-volume
          persistentVolumeClaim:
            claimName: {{ .Values.logs.existingClaim }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
