{{- if .Values.ssh.useSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "horovod.fullname" . }}
  labels:
    app: {{ template "horovod.name" . }}
    chart: {{ template "horovod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  host-key: {{ .Values.ssh.hostKey | quote }}
  host-key-pub: {{ .Values.ssh.hostKeyPub | quote }}
{{- end }}